vim.cmd [[ map <buffer> q gq ]]
vim.cmd [[ nmap <buffer> <Tab> = ]]
vim.cmd [[ nmap <buffer> cc :SemanticalCommit<cr> ]]
vim.cmd [[ nmap <buffer> Pp :PushCurrent<cr> ]]
vim.cmd [[ nmap <buffer> Fp :PullCurrent<cr> ]]
vim.cmd [[ nmap <buffer> bc :CreateBranch<cr> ]]
vim.cmd [[ nmap <buffer> bb :SwitchBranch<cr> ]]
