#!/bin/sh

echo "Linking stuff..."

ln -sf "$PWD/.bashrc" "/home/cherry/.bashrc"
ln -sf "$PWD/scripts" "/home/cherry/bin"
ln -sf "$PWD/.gitconfig" "/home/cherry/.gitconfig"

mkdir -p "/home/cherry/.local/bin" || true

for i in vim lynx tmux; do
	echo $i
	cd $i && sh ./setup
	cd -
done

echo "Finished ! :D"
