#!/bin/sh
set -e

echo "Installing packages..."

apt install fzy fd-find xclip software-properties-common
add-apt-repository ppa:neovim-ppa/stable
apt update
apt install neovim

ln -sf /usr/bin/fd-find /usr/bin/fd

clear

echo "Linking stuff..."

ln -sf "$PWD/.bashrc" "/home/cherry/.bashrc"
ln -sf "$PWD/scripts" "/home/cherry/bin"
ln -sf "$PWD/Music" "/home/cherry/Music"
ln -sf "$PWD/wallpapers" "/home/cherry/wallpapers"
ln -sf "$PWD/.gitconfig" "/home/cherry/.gitconfig"
ln -sf "$PWD/.git-coauthors" "/home/cherry/.git-coauthors"

mkdir -p "/home/cherry/.local/bin" || true

for i in vim lynx tmux kmonad; do
	echo $i
  cd $i && sudo sh ./setup
  cd -
done

echo "Finished ! :D"
