let mapleader=' '
source ~/.vim/plugs.vim

let g:UltiSnipsExpandTrigger="<c-l>"
let g:UltiSnipsJumpForwardTrigger="<c-l>"
let g:UltiSnipsJumpBackwardTrigger="<c-p>"

let g:UltiSnipsEditSplit="vertical"
