#!/bin/sh

echo "linking"

ln -sf "$PWD/vimrc" "/home/cherry/.vimrc"

echo "installing dependencies.."
apt install git make clang libtool-bin libxt-dev

echo "cloning"
git clone https://github.com/vim/vim /home/cherry/Downloads/packages/vim

# TO DO: check how to enable language interp
sh ./configure --with-features=huge --enable-python3interp=yes --enable-gui=auto

echo "building all..."
make
make install
