#!/bin/sh

echo "installing dependencies.."
apt install git make clang libtool-bin libxt-dev

echo "cloning"
git clone https://github.com/vim/vim /home/cherry/Downloads/packages/vim

# TODO: check how to enable language interp
sh ./configure --with-features=huge --enable-pythoninterp=yes --enable-rubyinterp=yes --enable-luainterp=yes --enable-gui=auto

echo "building all..."
make
make install

echo "linking"

ln -sf "$PWD/config" "/home/cherry/.vim"
