vim.cmd [[ augroup FORMATTING ]]
vim.cmd [[ autocmd! ]]
vim.cmd [[ autocmd BufWritePre * lua vim.lsp.buf.formatting()]]
vim.cmd [[ augroup END ]]

vim.cmd [[augroup highlight_yank]]
vim.cmd [[    autocmd!]]
vim.cmd [[    autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank({timeout = 40})]]
vim.cmd [[augroup END]]
vim.cmd [[]]
vim.cmd [[augroup CHERRY]]
vim.cmd [[    autocmd!]]
vim.cmd [[    " Remove whitespaces on save]]
vim.cmd [[    autocmd BufWritePre * %s/\s\+$//e]]
vim.cmd [[    " Remove whitespace highlight group because it's annoying]]
vim.cmd [[    autocmd BufWinEnter * highlight clear ExtraWhitespace]]
vim.cmd [[augroup END]]
