#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

## Autostart

function run {
 if ! pgrep $1 ;
 then
	 $@&
 fi
}

$HOME/.config/polybar/launch.sh --material

run mpd &
run dunst &
run compton &
run emacs --daemon &

run nm-applet
run volumeicon

run feh --bg-fill ~/Pictures/background.jpg &

run xrandr --output HDMI-1 --primary --mode 2560x1080 --left-of DVI-D-1 --mode 2560x1080

## Configuration

bspc monitor HDMI-1 -d 1 2 3 4 5 6
bspc monitor DVI-D-1 -d 7 8 9 0

bspc config border_width         7
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
