#!/usr/bin/perl

use strict;
use warnings;

use v5.14;

my $target = $ARGV[0];

exit 1 if not defined $target;

# TODO - change this to use proper perl grep.
my $result = `git ls-files | grep -i $target`;

my $count = () = $result =~ /src/g;

if (length($result) == 0) {
  exit 1;
}

if ($count > 1) {
   my @arr = split(' ', $result);

	 my @newarr;

	 for my $i (keys @arr) {
		 push @newarr, "$i: $arr[$i]\n";
	 }

	 say @newarr;

	 print "Select an item: ";
	 my $item = <STDIN>;
	 chomp $item;

	 my $filepath = $newarr[$item];
	 $filepath =~ tr/[0-9]: //d;

	 exec "$ENV{'EDITOR'} $filepath";

   exit 1;
}

exec "$ENV{'EDITOR'} $result";
