#!/bin/bash

db () {
	read -p "Database name: " dbname

  if [[ -n $dbname ]]; then
    docker exec -it postgres psql -U postgres -d $dbname
  else
    docker exec -it postgres psql -U postgres
  fi
}

"$@" #this lets you call the functions from the terminal
