#!/usr/bin/env bash

if [[ -f "package.json" ]]; then
	yarn prettier --write \"src/**/*.ts\" \"test/**/*.ts\"
  git add .
  git commit --no-verify --amend --no-edit
fi

git push origin $(git rev-parse --abbrev-ref HEAD) $@
