#!/usr/bin/env perl

use strict;
use warnings;

use v5.14;

my $filename = $ARGV[0] or die "Please provide a filename to follow on";

my $file = "$ENV{'HOME'}/bin/$filename";

sub create_perl_script_file {
	open my $script, '>', $file;
	print {$script} "#!/usr/bin/env perl" . "\n";
	print {$script} "\n";
	print {$script} "use strict;" . "\n";
	print {$script} "use warnings;" . "\n";
	print {$script} "\n";
	print {$script} "use v5.14;" . "\n";
	close $script;
}

if (-e $file) {
  system "$ENV{'EDITOR'} $file";
} else {
  create_perl_script_file();
  system "chmod +x $file";
  system "$ENV{'EDITOR'} $file";
}
