(require 'straight)
(defmacro package! (pkg)
  `(straight-use-package ,pkg))

(package! 'smex)
(package! 'better-defaults)
(package! 'ace-window)
(package! 'modus-themes)
(package! 'css-eldoc)
(package! 'elisp-slime-nav)
(package! 'f)
(package! 'fill-column-indicator)
(package! 'flx)
(package! 'flx-ido)
(package! 'flycheck)
(package! 'flycheck-pos-tip)
(package! 'highlight-escape-sequences)
(package! 'ido-at-point)
(package! 'ido-completing-read+)
(package! 'ido-vertical-mode)
(package! 'magit)
(package! 'markdown-mode)
(package! 'nodejs-repl)
(package! 'paredit)
(package! 'perspective)
(package! 'projectile)
(package! 'restclient)
(package! 'ripgrep)
(package! 'smartparens)
(package! 'visual-regexp)
(package! 'wgrep)
(package! 'whitespace-cleanup-mode)
(package! 'yasnippet)
;; (package! 'find-file-in-project) ;; Think about that
(package! 'multiple-cursors)
(package! 'ace-jump-mode)
(package! 'expand-region)
(package! 'prettier-js)
(package! 'typescript-mode)
(package! 'web-mode)
(package! 'company)
(package! 'eglot)
(package! 'zencoding-mode)
(package! 'npm-mode)
(package! 'crux)
(package! 'tree-sitter)
(package! 'tree-sitter-langs)
(package! 'vterm)
;; (package! 'god-mode) Thinking about this
(package! 'which-key)

(provide 'package)
