(straight-use-package 'vertico)
(straight-use-package 'savehist)
(straight-use-package 'marginalia)

;; (straight-use-package 'flx)
;; (straight-use-package 'flx-ido)
;; (straight-use-package 'smex)
;; (straight-use-package 'ido-vertical-mode)

(straight-use-package 'company-flx)
(straight-use-package 'company-quickhelp)
(straight-use-package 'company)

(straight-use-package 'perspective)
(straight-use-package 'ag)
(straight-use-package 'find-file-in-project)
(straight-use-package 'fzf)
(straight-use-package 'smart-window)

(straight-use-package 'typescript-mode)
(straight-use-package 'web-mode)
(straight-use-package 'yaml-mode)
(straight-use-package 'markdown-mode)
(straight-use-package 'flycheck)
(straight-use-package 'npm-mode)
(straight-use-package 'tide)
(straight-use-package 'format-all)
(straight-use-package 'clojure-mode)
(straight-use-package 'paredit)
(straight-use-package 'clj-refactor)

(straight-use-package 'crux)
(straight-use-package 'ace-jump-mode)
(straight-use-package 'multiple-cursors)
(straight-use-package 'iy-go-to-char)
(straight-use-package 'expand-region)
(straight-use-package 'buffer-move)

(straight-use-package 'gruber-darker-theme)
(straight-use-package 'magit)
(straight-use-package 'mood-line)
(straight-use-package 'bufler)
(straight-use-package 'exec-path-from-shell)
(straight-use-package 'yasnippet-snippets)
(straight-use-package 'yasnippet)
(straight-use-package 'key-chord)
(straight-use-package 'change-inner)
(straight-use-package 'hardcore-mode)
