- name: arch
  become: true
  become_user: root
  pacman:
    state: present
    name:
      - jre-openjdk
      - fzf
      - bat
      - exa
      - stow
      - lazygit
      - polybar
      - xclip
      - brave-bin
      - pavucontrol
      - flameshot
      - tmux
      - lua
      - elinks
      - kitty
      - dunst
      - mpd
      - mpv
      - mpc
      - ncmpcpp
      - fish
      - github-cli
      - i3-gaps
      - i3status
      - i3lock-color
      - sxhkd
      - visual-studio-code-bin
      - google-chrome
      - dbeaver
      - go
      - python
      - ttf-jetbrains-mono
      - ruby
      - picom
      - emacs
