local Utils = require("cherry.utils")

Utils.noremap("n", ";", ":", {noremap = true})
Utils.noremap('n', 'gl', '$', { noremap = true })
Utils.noremap('n', 'gh', '^', { noremap = true })
Utils.noremap('n', 'te', ':tabnew<CR>', { noremap = true })
Utils.noremap('n', 'Y', 'y$', { noremap = true })

-- Leader mappings
Utils.noremap('n', '<leader>fs', ':w<CR>', { noremap = true })
Utils.noremap('n', '<leader>ws', ':sp<CR>', { noremap = true })
Utils.noremap('n', '<leader>wv', ':vs<CR>', { noremap = true })
Utils.noremap('n', '<leader>wo', '<C-w>o', { noremap = true })
Utils.noremap('n', '<leader>qq', ':wqall<CR>', { noremap = true })
Utils.noremap('n', '<leader>bd', ':lua require("cherry.utils").quit()<CR>', { noremap = true })
Utils.noremap('n', '<leader>wd', ':lua require("cherry.utils").quit()<CR>', { noremap = true })
Utils.noremap('n', '<leader>bn', ':new<CR>', { noremap = true })
Utils.noremap('n', '<leader>h', '<C-w>h', { noremap = true })
Utils.noremap('n', '<leader>j', '<C-w>j', { noremap = true })
Utils.noremap('n', '<leader>k', '<C-w>k', { noremap = true })
Utils.noremap('n', '<leader>l', '<C-w>l', { noremap = true })
Utils.noremap('n', '<leader><CR>', ':lua require("cherry.utils").load_code()<CR>', { noremap = true })
